import {NavLink,Route,Routes,Link,Navigate} from 'react-router-dom';
import {useEffect,useState} from 'react';
import {LayoutDashboard,BookOpen,FileText,Files,Menu,Search,Bell,Download,ExternalLink,Maximize,FileX,GraduationCap,Loader2} from 'lucide-react';
import {standards,subjects,years,getPdf,loadPapers} from './services/api';
import Generator,{Papers} from './Generator';

const nav=[['/app/dashboard',LayoutDashboard,'Dashboard'],['/app/question-bank',BookOpen,'Question Bank'],['/app/question-paper-generator',FileText,'Question Paper Generator'],['/app/papers',Files,'Generated Papers']] as const;
export default function Shell(){const [open,setOpen]=useState(true);
 return <div className="min-h-screen flex text-slate-800">
  <aside className={`${open?'w-64':'w-16'} shrink-0 bg-gradient-to-b from-slate-950 to-indigo-950 text-slate-200 transition-all hidden sm:block`}>
   <div className="h-16 flex items-center gap-2 px-4 font-bold text-white"><Link to="/" title="Back to JSSquared" className="flex items-center gap-2"><GraduationCap className="text-indigo-300"/>{open&&'EduPaper'}</Link></div>
   <nav className="p-2 space-y-1">{nav.map(([to,I,l])=><NavLink key={to} to={to} className={({isActive})=>`flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm transition ${isActive?'bg-indigo-500 text-white shadow':'hover:bg-white/10'}`}><I size={18}/>{open&&l}</NavLink>)}</nav></aside>
  <div className="flex-1 min-w-0">
   <header className="h-16 bg-white border-b flex items-center gap-3 px-4"><button onClick={()=>setOpen(!open)}><Menu/></button>
    <div className="relative flex-1 max-w-md"><Search size={16} className="absolute left-3 top-3 text-slate-400"/><input placeholder="Search papers, subjects…" className="w-full pl-9 pr-3 py-2 rounded-lg bg-slate-100 text-sm outline-none"/></div>
    <Bell size={20} className="ml-auto text-slate-500"/><div className="w-9 h-9 rounded-full bg-indigo-600 text-white grid place-items-center text-sm">T</div></header>
   <main className="p-4 sm:p-8 max-w-6xl mx-auto"><Routes><Route index element={<Navigate to="dashboard" replace/>}/><Route path="dashboard" element={<Dashboard/>}/><Route path="question-bank" element={<Bank/>}/><Route path="question-paper-generator" element={<Generator/>}/><Route path="papers" element={<Papers/>}/></Routes></main>
   <nav className="sm:hidden fixed bottom-0 inset-x-0 bg-white border-t flex justify-around py-2">{nav.map(([to,I])=><NavLink key={to} to={to} className={({isActive})=>isActive?'text-indigo-600':'text-slate-400'}><I/></NavLink>)}</nav></div></div>}

function Dashboard(){const p=loadPapers();const mo=[['Apr',4],['May',7],['Jun',5],['Jul',9],['Aug',12],['Sep',8+p.length]];
 const stats=[['Total Question Papers',48],['Available Subjects',9],['Question Bank Resources',1240],['Papers Generated',36+p.length]];
 return <div className="space-y-6"><div><h1 className="text-3xl font-bold text-slate-900">Welcome back, Teacher!</h1><p className="text-slate-500">Manage question banks and create examination papers effortlessly.</p></div>
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{stats.map(([l,v])=><div key={l} className="bg-white rounded-2xl p-5 shadow-sm"><div className="text-3xl font-bold text-indigo-700">{v}</div><div className="text-sm text-slate-500">{l}</div></div>)}</div>
  <div className="grid md:grid-cols-2 gap-4">{[[BookOpen,'Question Bank','Explore previous-year question papers organized by standard, subject, and academic year.','Explore Question Bank','/app/question-bank'],[FileText,'Question Paper Generator','Generate customized examination papers with randomized questions from your question bank.','Generate Paper','/app/question-paper-generator']].map(([I,t,d,b,to]:any)=>
   <div key={t} className="rounded-2xl p-6 text-white bg-gradient-to-br from-slate-900 via-indigo-900 to-indigo-600 shadow-lg"><I size={32}/><h2 className="text-xl font-semibold mt-3">{t}</h2><p className="text-indigo-100 text-sm my-2">{d}</p><Link to={to} className="inline-block mt-2 bg-white text-indigo-900 font-medium px-4 py-2 rounded-lg hover:scale-105 transition">{b}</Link></div>)}</div>
  <div className="grid md:grid-cols-2 gap-4"><div className="bg-white rounded-2xl p-5 shadow-sm"><h3 className="font-semibold mb-3">Recent activity</h3><ul className="text-sm space-y-2 text-slate-600">
   {p.slice(0,3).map(x=><li key={x.id}>Generated “{x.meta.exam}” – {x.meta.subject} <span className="text-slate-400">· {x.date}</span></li>)}<li>Viewed 10th Mathematics 2023 <span className="text-slate-400">· 2 days ago</span></li><li>Viewed 12th Physics 2024 <span className="text-slate-400">· 4 days ago</span></li></ul></div>
   <div className="bg-white rounded-2xl p-5 shadow-sm"><h3 className="font-semibold mb-3">Papers generated by month</h3><div className="flex items-end gap-3 h-32">{mo.map(([m,v]:any)=><div key={m} className="flex-1 text-center text-xs"><div className="bg-gradient-to-t from-indigo-700 to-indigo-400 rounded-t" style={{height:v*8}}/>{m}</div>)}</div></div></div></div>}

const Card=({on,onClick,children}:any)=><button onClick={onClick} className={`p-5 rounded-2xl text-left border-2 transition hover:-translate-y-0.5 hover:shadow-md ${on?'border-indigo-600 bg-indigo-50':'border-transparent bg-white shadow-sm'}`}>{children}</button>;
function Bank(){const [std,setStd]=useState('');const [sub,setSub]=useState('');const [year,setYear]=useState(0);
 const sn=standards.find(s=>s.id===std)?.name;
 return <div className="space-y-6"><div><h1 className="text-3xl font-bold">Question Bank</h1><p className="text-slate-500">Access previous-year question papers in just a few clicks.</p></div>
  <div className="text-sm text-slate-500">Dashboard › Question Bank{sn&&<> › <button onClick={()=>{setSub('');setYear(0)}}>{sn}</button></>}{sub&&<> › <button onClick={()=>setYear(0)}>{sub}</button></>}{year>0&&<> › {year}</>}</div>
  <h2 className="font-semibold">1. Select Standard</h2><div className="grid sm:grid-cols-3 gap-4">{standards.map(s=><Card key={s.id} on={std===s.id} onClick={()=>{setStd(s.id);setSub('');setYear(0)}}><GraduationCap className="text-indigo-600 mb-2"/>{s.name}</Card>)}</div>
  {std&&<><h2 className="font-semibold">2. Select Subject</h2><div className="grid grid-cols-2 sm:grid-cols-4 gap-4">{subjects[std].map(s=><Card key={s} on={sub===s} onClick={()=>{setSub(s);setYear(0)}}><BookOpen className="text-indigo-600 mb-2" size={20}/>{s}</Card>)}</div></>}
  {sub&&<><h2 className="font-semibold">3. Select Year</h2><div className="grid grid-cols-2 sm:grid-cols-4 gap-4">{years.map(y=><Card key={y} on={year===y} onClick={()=>setYear(y)}><FileText className="text-red-500 mb-1" size={20}/><b>{y}</b><div className="text-xs text-emerald-600">PDF available</div></Card>)}</div></>}
  {year>0&&<Viewer std={std} sub={sub} year={year} sn={sn!}/>}</div>}

function Viewer({std,sub,year,sn}:any){const [d,setD]=useState<any>();const [load,setLoad]=useState(true);
 useEffect(()=>{setLoad(true);getPdf(std,sub,year).then(r=>{setD(r);setLoad(false)})},[std,sub,year]);
 if(load)return <div className="h-96 bg-white rounded-2xl grid place-items-center"><Loader2 className="animate-spin text-indigo-600"/></div>;
 if(!d)return <div className="bg-white rounded-2xl p-12 text-center text-slate-500"><FileX className="mx-auto mb-2" size={40}/>No question paper is available for this selection yet.</div>;
 return <div className="bg-white rounded-2xl shadow-sm p-4 space-y-3"><div className="flex flex-wrap items-center gap-3 text-sm"><span><b>{sn}</b> · {sub} · {year} · <code>{d.name}</code></span>
  <div className="ml-auto flex gap-2"><a href={d.url} download={d.name} className="btn flex gap-1 items-center bg-indigo-600 text-white px-3 py-1.5 rounded-lg"><Download size={14}/>Download</a><a href={d.url} target="_blank" className="flex gap-1 items-center border px-3 py-1.5 rounded-lg"><ExternalLink size={14}/>New tab</a><button onClick={()=>document.getElementById('pdf')?.requestFullscreen()} className="flex gap-1 items-center border px-3 py-1.5 rounded-lg"><Maximize size={14}/>Full screen</button></div></div>
  <iframe id="pdf" src={d.url} className="w-full h-[70vh] rounded-lg border" title="PDF"/><p className="text-xs text-slate-400">Page navigation and zoom are provided by the browser's built-in PDF viewer.</p></div>}
